# @summary
# Vision enrichment helpers that extract markdown images and call a VLM via
# LiteLLM for caption/OCR/tag extraction during ingestion.
# Exports: ensure_vision_ready, generate_vision_notes
# Deps: base64, json, re, src.platform.llm, src.ingest.common.types, src.ingest.common.utils
# @end-summary
"""Vision enrichment helpers for multimodal ingestion, backed by LiteLLM."""

from __future__ import annotations

import base64
import binascii
import json
import logging
import mimetypes
import re
from dataclasses import dataclass
from pathlib import Path

from src.ingest.common.types import IngestionConfig
from src.ingest.common.utils import parse_json_object
from src.platform.llm import get_llm_provider

logger = logging.getLogger(__name__)

_IMAGE_REF_PATTERN = re.compile(
    r"!\[(?P<alt>[^\]]*)\]\((?P<src>[^)]+)\)",
    flags=re.IGNORECASE,
)
_DATA_URL_PATTERN = re.compile(
    r"^data:(?P<mime>image/[-+.\w]+)?;base64,(?P<data>.+)$",
    flags=re.IGNORECASE | re.DOTALL,
)


@dataclass
class VisionImageCandidate:
    """Resolved image candidate extracted from markdown content.

    Attributes:
        figure_label: Display label for the figure (e.g., ``Figure 1``).
        alt_text: Markdown alt text for the image, when present.
        source_ref: Resolved source reference (file path or ``data-url``).
        image_b64: Base64-encoded image bytes.
        mime_type: MIME type for the image (e.g., ``image/png``).
    """

    figure_label: str
    alt_text: str
    source_ref: str
    image_b64: str
    mime_type: str


@dataclass
class VisionDescription:
    """Structured visual description generated by a VLM call.

    Attributes:
        figure_label: Display label for the figure (e.g., ``Figure 1``).
        source_ref: Resolved source reference (file path or ``data-url``).
        caption: Short caption describing the figure.
        visible_text: OCR-like text visible in the image (best effort).
        tags: Keyword-like tags for retrieval.
    """

    figure_label: str
    source_ref: str
    caption: str
    visible_text: str
    tags: list[str]

    def as_note(self) -> str:
        """Render a compact text note appended into cleaned content.

        Returns:
            A single-line note encoding the caption, optional OCR text, and tags.
        """
        parts: list[str] = [f"{self.figure_label}: {self.caption}"]
        if self.visible_text:
            parts.append(f"text={self.visible_text}")
        if self.tags:
            parts.append(f"tags={', '.join(self.tags[:8])}")
        return " | ".join(parts)


# ── Image extraction helpers ───────────────────────────────────────────


def _decode_data_url(src: str) -> tuple[bytes, str] | None:
    """Decode a base64 data URL into image bytes.

    Args:
        src: Candidate source string.

    Returns:
        Tuple of ``(image_bytes, mime_type)`` when ``src`` is a valid data URL,
        otherwise ``None``.
    """
    match = _DATA_URL_PATTERN.match(src.strip())
    if not match:
        return None
    mime_type = (match.group("mime") or "image/png").lower()
    data_blob = match.group("data").strip()
    try:
        return base64.b64decode(data_blob), mime_type
    except (ValueError, binascii.Error):
        return None


def _resolve_file_image_bytes(
    src: str,
    *,
    source_path: Path,
) -> tuple[bytes, str, str] | None:
    """Resolve a local markdown image src to bytes and MIME metadata.

    Args:
        src: Markdown image source.
        source_path: Path to the markdown source file (used for relative refs).

    Returns:
        Tuple of ``(image_bytes, mime_type, resolved_path)`` or ``None`` when
        the reference cannot be resolved to a local file.
    """
    cleaned = src.strip().strip("<>").split(" ", 1)[0]
    if not cleaned:
        return None
    if cleaned.startswith(("http://", "https://")):
        return None
    if cleaned.startswith("file://"):
        candidate_path = Path(cleaned[7:])
    else:
        candidate_path = Path(cleaned)
        if not candidate_path.is_absolute():
            candidate_path = source_path.parent / candidate_path
    candidate_path = candidate_path.resolve()
    if not candidate_path.exists() or not candidate_path.is_file():
        return None
    image_bytes = candidate_path.read_bytes()
    guessed_mime, _ = mimetypes.guess_type(str(candidate_path))
    mime_type = (guessed_mime or "image/png").lower()
    return image_bytes, mime_type, str(candidate_path)


def _extract_image_candidates(
    markdown: str,
    *,
    source_path: Path,
    max_figures: int,
    max_image_bytes: int,
) -> list[VisionImageCandidate]:
    """Extract local and data-url image references from markdown.

    Args:
        markdown: Markdown content to scan.
        source_path: Path to the markdown source file for resolving relative refs.
        max_figures: Maximum number of candidates to return.
        max_image_bytes: Maximum allowed image size in bytes.

    Returns:
        List of resolved `VisionImageCandidate` entries.
    """
    candidates: list[VisionImageCandidate] = []
    for idx, match in enumerate(_IMAGE_REF_PATTERN.finditer(markdown)):
        if len(candidates) >= max_figures:
            break
        alt_text = (match.group("alt") or "").strip()
        src = (match.group("src") or "").strip()
        figure_label = f"Figure {idx + 1}"

        decoded = _decode_data_url(src)
        if decoded is not None:
            image_bytes, mime_type = decoded
            source_ref = "data-url"
        else:
            resolved = _resolve_file_image_bytes(src, source_path=source_path)
            if resolved is None:
                continue
            image_bytes, mime_type, source_ref = resolved

        if not image_bytes or len(image_bytes) > max_image_bytes:
            continue
        candidates.append(
            VisionImageCandidate(
                figure_label=figure_label,
                alt_text=alt_text,
                source_ref=source_ref,
                image_b64=base64.b64encode(image_bytes).decode("ascii"),
                mime_type=mime_type,
            )
        )
    return candidates


# ── VLM calls via LiteLLM ─────────────────────────────────────────────

_VISION_PROMPT = (
    "You are an OCR-and-figure-analysis assistant for retrieval indexing. "
    "Return JSON only with keys: caption (string), visible_text (string), tags (array of strings). "
    "Keep caption under 200 chars, visible_text under 200 chars, and max 8 tags."
)


def _describe_image(
    candidate: VisionImageCandidate,
    config: IngestionConfig,
) -> VisionDescription:
    """Call a VLM via LiteLLM and normalize the result.

    Args:
        candidate: Resolved image candidate to describe.
        config: Ingestion configuration controlling vision parameters.

    Returns:
        A normalized `VisionDescription`.
    """
    provider = get_llm_provider()
    response = provider.vision_completion(
        prompt=_VISION_PROMPT,
        image_b64=candidate.image_b64,
        mime_type=candidate.mime_type,
        model_alias="vision",
        temperature=config.vision_temperature,
        max_tokens=config.vision_max_tokens,
    )
    parsed = parse_json_object(response.content)
    caption = str(parsed.get("caption", "")).strip() or "No caption generated."
    visible_text = str(parsed.get("visible_text", "")).strip()
    tags_raw = parsed.get("tags")
    tags = [str(tag).strip() for tag in tags_raw] if isinstance(tags_raw, list) else []
    tags = [tag for tag in tags if tag][:8]
    return VisionDescription(
        figure_label=candidate.figure_label,
        source_ref=candidate.source_ref,
        caption=caption[:240],
        visible_text=visible_text[:260],
        tags=tags,
    )


# ── Readiness check ───────────────────────────────────────────────────


def ensure_vision_ready(config: IngestionConfig) -> None:
    """Validate that the configured vision model is reachable via LiteLLM.

    Args:
        config: Ingestion configuration controlling whether vision is enabled.

    Raises:
        RuntimeError: If vision processing is enabled but the configured model is
            not reachable.
    """
    if not config.enable_vision_processing:
        return
    provider = get_llm_provider()
    if not provider.is_available(model_alias="vision"):
        raise RuntimeError(
            "Vision model is not reachable via LiteLLM. "
            "Check RAG_LLM_VISION_MODEL / Router YAML config."
        )


# ── Public API ─────────────────────────────────────────────────────────


def generate_vision_notes(
    markdown: str,
    *,
    source_path: Path,
    config: IngestionConfig,
) -> tuple[list[str], int]:
    """Generate figure notes from markdown images using a configured VLM backend.

    Args:
        markdown: Markdown content to scan for image references.
        source_path: Source file path used for resolving relative image refs.
        config: Ingestion configuration controlling vision extraction limits.

    Returns:
        Tuple of ``(notes, described_count)`` where ``notes`` are compact strings
        suitable for appending to cleaned content.
    """
    candidates = _extract_image_candidates(
        markdown,
        source_path=source_path,
        max_figures=max(1, config.vision_max_figures),
        max_image_bytes=max(16_384, config.vision_max_image_bytes),
    )
    if not candidates:
        return [], 0

    notes: list[str] = []
    described_count = 0
    for candidate in candidates:
        description = _describe_image(candidate, config)
        notes.append(description.as_note())
        described_count += 1
    return notes, described_count
